### ISSUE TITLE
https://remix.ethereum.org new version. Button "add local files" doesn't work.

### ISSUE THREAD

**Issue by IvanMolodtsov** [ethereum/remix-ide#2097] opened 2019-06-19 14:08 UTC
File explorer tab. Button "add local files" doesn't work. Checked on Google Chrome and Mozila Firefox. Instead of opening "choose file" window it expands/wraps browser folder.

**Comment by LianaHus** [comment] 2019-06-26 18:32
just checked on master it works for me. @yann300 are you able to reproduce it?

**Comment by LianaHus** [comment] 2019-06-26 18:34
it's broken on alpha though.

**Comment by LianaHus** [comment] 2019-06-27 09:30
fixed on alpha. I'm closing the issue, thanks for the report

**Closed by LianaHus** 2019-06-27 09:30 UTC
Labels: bug, ready
