### ISSUE TITLE
Max Call Stack Exceeded

### ISSUE THREAD

**Issue by willdeuschle** [ethereum/remix-ide#1380] opened 2018-06-30 23:09 UTC
I'm getting the same error as #1373 when I try to execute `npm run build`, and it was not resolved by switching to node 9.11.2.

`SyntaxError: Maximum call stack size exceeded while parsing /Users/willdeuschle/Dev/gitcoin/remix-ide/node_modules/solc/soljson.js while parsing file: /Users/willdeuschle/Dev/gitcoin/remix-ide/node_modules/solc/soljson.js`

MacOS 10.13.4, node v9.11.2, npm 5.6.0.

**Comment by sekmet** [comment] 2018-07-05 16:38
Same issue here.

SyntaxError: Maximum call stack size exceeded while parsing .../remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js

Debian 9, node 10.5.0, npm 6.1.0

**Comment by yann300** [comment] 2018-08-23 10:55
That is fixed by now (added `--exclude solc` in the browserify script.

**Closed by yann300** 2018-08-23 10:55 UTC
Labels: Installation, bug

**Comment by prashantprabhakar** [comment] 2018-09-24 17:58
@yann300 Facing the issue with `Current version:0.4.24+commit.e67f0147.Emscripten.clang`. Seems the issue is not resolved yet.

**Comment by sachushaji** [comment] 2018-12-21 06:19
@yann300 I am also facing a similar issue with the current remix ide. I will get the error while copy pasting the code.
![screenshot from 2018-12-21 11-43-44](https://user-images.githubusercontent.com/15767732/50327722-3ea60d80-0516-11e9-97a2-4f5f5e96bbb5.png)
But after I make a small change like adding space or anything else, the code recompiles and everything works perfectly.
