### ISSUE TITLE
Store scaling settings for user

### ISSUE THREAD

**Issue by hgedia** [ethereum/remix-ide#1592] opened 2018-11-06 16:23 UTC
Usually on closing the tab & revisiting the remix url , the font scaling is re-set. It would be great if this could be maintained.

Steps to reproduce:
1. Hit + key to increase font size
2. Close tab
3. Re-visit in a new tab.

**Comment by LianaHus** [comment] 2018-11-12 14:46
duplicate of https://github.com/ethereum/remix-ide/issues/150

**Comment by LianaHus** [comment] 2018-11-12 14:46
duplicate of https://github.com/ethereum/remix-ide/issues/150

**Closed by LianaHus** 2018-11-12 14:46 UTC
Labels: UI, duplicate
