### ISSUE TITLE
Run & Deploy Buttons

### ISSUE THREAD

**Issue by schartnerc** [ethereum/remix-ide#2748] opened 2020-04-17 01:25 UTC
The buttons in the Run & Deploy Plugin are are transparent and only show up if hovered over them.

**Comment by LianaHus** [comment] 2020-07-23 13:20
hi @schartnerc , could you please add some details. which theme do you use and which buttons exactly do you mean?

**Comment by LianaHus** [comment] 2020-07-28 10:07
closing, can't reproduce. please reopen if you have more details

**Closed by LianaHus** 2020-07-28 10:07 UTC
Labels: UI
