### ISSUE TITLE
Having trouble verifying a contract on etherscan.io

### ISSUE THREAD

**Issue by memorysky** [ethereum/remix-ide#1376] opened 2018-06-25 02:56 UTC
I'm trying to verify a contract on etherscan.io.

The contract itself has a number of imports and libraries and has been deployed using remix.In our code, we imported other code like [import 'http://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20/MintableToken.sol'].

I've copy/pasted the code from all the .sol files into the validation textbox on etherscan, have selected the same compiler version,but failed.I don't get it why I get always such error:
![image](https://user-images.githubusercontent.com/5716632/41828111-f7d6a5dc-7865-11e8-92c8-6407686f218d.png)

**Comment by techieanant** [comment] 2018-06-28 14:48
@memorysky It might be due to either: 

- Choosing the wrong compiler version OR

- Keeping Optimization enabled 

Try setting the optimization enabled to NO and see if that works.

![image](https://user-images.githubusercontent.com/7658579/42041798-af764df8-7ac0-11e8-9356-5335c588a192.png)

**Comment by NEO2756** [comment] 2018-07-25 23:01
deployed using remix.
1. optimization is enbaled (checked)
2. compiler version 0.4.24+commit.e67f0147 (checked on both sides)
still Not verified. Pls help

TIA

**Comment by NEO2756** [comment] 2018-08-06 03:33
I managed to solve the problem via using flat file. If you have multiple *.sol files , use any flattner to make a single flat file. Compile this flat file and deploy it rather than multiple files. Use the same file as source file at etherscan.io. Hope this helps.

**Comment by troowala** [comment] 2018-08-06 03:54
yep already using a flattened file that is not the issue in my case .... im pretty certain this issue happens with flattened files too if one were using enable optimization selected in remix during publishing the contract and then tried to verify, that is the crux of the issue here.

**Comment by kot-begemot** [comment] 2018-08-24 15:14
Same issue here. I compiled flattened contract on Remix and then deployed it to blockchain. Now I can not verify it. Used same parameters as when I was compiling it. 

I checked the source code comparison: they indeed looks different

https://etherscan.io/verifyContract2

Any thoughts are appreciated

**Comment by yosrahelal** [comment] 2018-09-18 09:32
@kot-begemot did you solve your problem ? please ?

**Comment by yann300** [comment] 2019-05-11 15:19
the issue was related to https://github.com/ethereum/solidity/issues/5234 .
That should be fixed now.  i m closing it, please reopen if the issue is still here

**Closed by yann300** 2019-05-11 15:19 UTC
