### ISSUE TITLE
[Static Analysis] Display the classification flag in the view

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1529] opened 2018-09-19 08:36 UTC
from here https://github.com/ethereum/remix/blob/master/remix-analyzer/src/solidity-analyzer/modules/algorithmCategories.js

**Comment by LianaHus** [comment] 2020-07-22 16:24
@Aniket-Engg

**Comment by Aniket-Engg** [comment] 2020-07-23 05:57
duplicate of https://github.com/ethereum/remix-ide/issues/2821
Perhaps this can be tracked together with https://github.com/ethereum/remix-ide/issues/2812

**Comment by LianaHus** [comment] 2020-07-27 14:35
I'm closing this as we have #2821

**Closed by LianaHus** 2020-07-27 14:35 UTC
Labels: bounty-worthy, enhancement
