### ISSUE TITLE
Verifying Remix published Source Code on etherscan

### ISSUE THREAD

**Issue by troowala** [ethereum/remix-ide#1422] opened 2018-07-24 01:58 UTC
I have verified several contracts on etherscan in the past without much issues but this time it is getting weird, makes me suspect there is some bug with etherscan in regards to contracts recently published with remix.

Contract address is
0xb3f5687d11ec10f04e00c42b4952f0352ae1762b

Contract Name is
BurnableCrowdsaleToken

Code for verification
https://gist.github.com/33c1382a617d2b3a906db1946ab4c3e2

SafeMathLib for the contract
0xe2dc6dfb40cbca1bbe61bd3f33cf40af860dbd59

Here are the tx's.
Token Contract https://etherscan.io/tx/0x98ae3decf0df1878bad78c07d5ce5bb5e9657547c4b2f53d464be546a076ebad

SafeMathLib https://etherscan.io/tx/0x44f47776fcb0eea4c2c45e23da87e67dec47d5362aee8440c7324266900eff5b

Constructor Arguments ABI
00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000010456e68616e63656420536f63696574790000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034553540000000000000000000000000000000000000000000000000000000000

Solidity Compiler version
0.4.24+commit.e67f0147

Code was compiled and published using remix.ethereum.org with "Enable optimization" selected.

I have tried every combination on the etherscan website in regards to optimization both yes & no and also using the https://etherscan.io/verifyContract2?a= link and specifying runs as 0 and 200 (default) but nothing seems to match.

Im out of ideas and any suggestions , feedback on trying something else would be very much appreciated.

Thanks

**Comment by yann300** [comment] 2018-07-24 09:47
i gave a try on rinkeby and that seems to work
https://rinkeby.etherscan.io/address/0xe9eca24adf0c8f925122f333867750ef7c8f4557#code
have you specified input parameters? what was the values?

**Comment by whrool** [comment] 2018-07-24 10:57
@yann300 Thank you for your help. I do it on the mainnet . And below is my contract info.
Network：mainnet
My contract address：0x04dbd7049675d114b8aafb4fe812afc8d4908c84
Contract Name：OTCChain
Contract source：https://gist.github.com/whrool/e0fbdc4636272ce658b0fb3fb0764d36
Optimization：true
Parameters：000000000000000000000000000000000000000000000000000000174876e800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000084f5443436861696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044f54434300000000000000000000000000000000000000000000000000000000

**Comment by troowala** [comment] 2018-07-24 22:54
Hello yann300 , i just retried it on rinkeby and same issue. did you also publish the contract using the current online version of remix ? 

parameters are
name : enhanced society
symbol : EST
supply : 0
decimals : 18
mintable : true

i also notice you have marked this as a bug , so are you now able to replicate this too ? 

also i noticed the first 201 characters of compiled bytecode match when optimization in etherscan verification is selected to no instead of yes even though optimization enabled was checked in remix and when selecting optimization yes it barely matches past the first 15 characters of the bytecode.

it is definitely not behaving normally as in the past i have verified several contracts without running into this issue. 

thanks for your help

**Comment by yann300** [comment] 2018-07-25 08:36
I am not able to replicate unfortunately ... I will try with the same param.
what is the encoded value you put fr encoded param in etherscan?

**Comment by troowala** [comment] 2018-07-25 09:43
00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000010456e68616e63656420536f63696574790000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034553540000000000000000000000000000000000000000000000000000000000

**Comment by troowala** [comment] 2018-08-01 03:07
Hello , any update on this issue ? This is consistently happening with remix.ethereum.org contracts and i can recreate this for you if you like via screen share. Infact you could simply deploy the MyAdvancedToken contract from ethereums website and try and verify it on ropsten and you will see the contract will not verify if optimization is selected.

Can you please confirm what non-exposed compiler settings are being passed by remix when optimization is set to that these contracts published with enable optimization using remix can be verified ?

**Comment by yann300** [comment] 2018-08-01 08:43
@troowala could you post or PM me the address of the contract you are trying to verify?

**Comment by yann300** [comment] 2018-08-02 15:47
I could verify it against solidity 0.4.24 and remix 0.6.4 (optimisation enable)
https://rinkeby.etherscan.io/address/0x66d3675f703a8292d629b1ca93270084d932401f#code

Are you using The API 1.0 or API 2.0 for verifying the contract on etherscan?

**Comment by troowala** [comment] 2018-08-03 01:42
i have tried both API versions on etherscan. See attached screenshot with v2 of the API as well.

I'm also selecting v0.4.24+commit.e67f0147 compiler and the version of remix im using is the one running on remix.ethereum.org 

![screenshot from 2018-08-03 11-40-21](https://user-images.githubusercontent.com/9698107/43619596-0e9050a0-9712-11e8-9a21-98b577a14dd2.png)

**Comment by troowala** [comment] 2018-08-06 03:05
@whrool Im aware of alternate ways to publish and verify the contracts so thanks but have you tried with the option enable optimization for contracts published using remix.ethereum.org ?  that is the method that is not working and has a bug that im raising.  and any workaround you suggest is only or contracts going forward in the future but if a contract has been published with remix.ethereum.org and had enable optimization selected it is not verifying. so is there a way to verify something published using this process ? not an alternate process of publishing contracts. cheers

**Comment by yann300** [comment] 2018-08-06 07:16
> but if a contract has been published with remix.ethereum.org and had enable optimization selected it is not verifying.

I am confused cause i was able to deploy it on Rinkeby:
could you record a screencast please? that ill help to figure out what can be the issue..

![screenshot from 2018-08-06 09 11 19](https://user-images.githubusercontent.com/6940742/43702140-07305456-9959-11e8-9a32-66fd290ffa6e.png)

**Comment by yann300** [comment] 2018-08-06 07:27
@whrool what are the decoded input parameters you've set for your contract?

**Comment by troowala** [comment] 2018-08-06 22:54
![screenshot from 2018-08-03 11-40-21](https://user-images.githubusercontent.com/9698107/43744870-70d223a0-9a1f-11e8-86a5-0a4ff1e15f87.png)

**Comment by yann300** [comment] 2018-08-07 07:12
@troowala I mean a little video,
btw which browser are you on?

**Comment by whrool** [comment] 2018-08-09 07:56
#### Firstly, I generate the bytecode of my source code  on the etherscan.io. Here i choose whatever a contract. As follows:
![image](https://user-images.githubusercontent.com/7413974/43713003-b2ef69c0-99aa-11e8-8766-97d352bbfd74.png)
#### Secondly, Use our source code to generate bytecode.
![image](https://user-images.githubusercontent.com/7413974/43713563-991d9362-99ac-11e8-8a62-429d2e2a39af.png)
#### Finally,we get the bytecode and ABI.
<img width="1158" alt="token3" src="https://user-images.githubusercontent.com/7413974/43713632-d77802aa-99ac-11e8-8b50-e9b4c8a057cd.png">

![image](https://user-images.githubusercontent.com/7413974/43713639-dce2face-99ac-11e8-87a9-343c43a04f70.png)
#### Use the bytecode and ABI to deploy contract.
![image](https://user-images.githubusercontent.com/7413974/43713763-5311737e-99ad-11e8-9f9f-43eec141e224.png)
#### Then we get the txhash.
![image](https://user-images.githubusercontent.com/7413974/43713779-62a994d8-99ad-11e8-8244-bfc6560ba9c2.png)
#### Query the tx on the etherscan.io
![image](https://user-images.githubusercontent.com/7413974/43713845-9a51daf8-99ad-11e8-8f5b-f9c4bb6872b8.png)
#### After the contract created successfully, we use the the source code (in the second step we provide) to verify the contract.
<img width="1056" alt="qq20180807-115231 2x" src="https://user-images.githubusercontent.com/7413974/43881387-9f92a3fc-9bde-11e8-81b5-ce6455127c14.png">

![image](https://user-images.githubusercontent.com/7413974/43881375-959233d6-9bde-11e8-8cde-06123e1d59f5.png)

**Comment by troowala** [comment] 2018-08-10 01:27
okay so this essentially means i have to publish a second identical contract on the mainnet and not use remix but a JS or python script instead ?

and will this only verify the newly published contract or also the previously published original one as etherscan will automatically pick up the first contracts source code as they have identical bytecode  ? 

thanks

**Comment by yann300** [comment] 2018-08-10 09:13
@whrool @troowala  that would work yes although that's a lot of manual action. I still would like to be able to reproduce cause. I could deploy deploy from remix and verify (rinkeby and mainet)..
@whrool could you send the decoded input parameter you use?
@troowala are you in chrome? could you record a little screencast please?

**Comment by troowala** [comment] 2018-08-13 00:42
please see attached recording , it shows a simple contract such as greeter.sol not verifying when enable optimization is selected. 

https://drive.google.com/file/d/1YiFcuKcOpWQR2OnHXGBzNUhIPhDgjyZo/view

it says that contract seems to be compiled with no optimization even when the video clearly shows enable optimization was selected.

and when trying to reverify with no optimization in etherscan , it shows contract name not found. https://drive.google.com/file/d/1LWQZ7UJ8gQBJYXlSNj-d3OkyBypeJf3z/view

so either ways if enable optimization is selected it does not verify. same issue with v2 of the verify api on etherscan as well.

hope you can guide regarding a solution now and have this bug resolved.

thanks

**Comment by whrool** [comment] 2018-08-13 03:47
@yann300 This my contract address 0x216CbfD5Bd8e3f3bBc83c9a62243DA5306B2aC16

**Comment by yann300** [comment] 2018-08-13 07:57
@troowala could you send the greeter code please? I tried with another version and i could verify it without any problem. also are you sure that solidity 0.4.24 is selected in the settings tab?

**Comment by yann300** [comment] 2018-08-13 08:13
@whrool 
you sent details:
```
Network：mainnet
My contract address：0x04dbd7049675d114b8aafb4fe812afc8d4908c84
Contract Name：OTCChain
Contract source：https://gist.github.com/whrool/e0fbdc4636272ce658b0fb3fb0764d36
Optimization：true
Parameters：000000000000000000000000000000000000000000000000000000174876e800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000084f5443436861696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044f54434300000000000000000000000000000000000000000000000000000000
```
but OTCChain is not there, is it IIIBTCToken?

**Comment by yann300** [comment] 2018-08-13 08:26
> You can refer the last contract I use.

could you post or pm the code and input params of this contract?

**Comment by whrool** [comment] 2018-08-13 08:28
The code(no input params) :
```
pragma solidity 0.4.24;

contract Token {

    /// @return total amount of tokens
    function totalSupply() constant returns (uint supply) {}

    /// @param _owner The address from which the balance will be retrieved
    /// @return The balance
    function balanceOf(address _owner) constant returns (uint balance) {}

    /// @notice send `_value` token to `_to` from `msg.sender`
    /// @param _to The address of the recipient
    /// @param _value The amount of token to be transferred
    /// @return Whether the transfer was successful or not
    function transfer(address _to, uint _value) returns (bool success) {}

    /// @notice send `_value` token to `_to` from `_from` on the condition it is approved by `_from`
    /// @param _from The address of the sender
    /// @param _to The address of the recipient
    /// @param _value The amount of token to be transferred
    /// @return Whether the transfer was successful or not
    function transferFrom(address _from, address _to, uint _value) returns (bool success) {}

    /// @notice `msg.sender` approves `_addr` to spend `_value` tokens
    /// @param _spender The address of the account able to transfer the tokens
    /// @param _value The amount of wei to be approved for transfer
    /// @return Whether the approval was successful or not
    function approve(address _spender, uint _value) returns (bool success) {}

    /// @param _owner The address of the account owning tokens
    /// @param _spender The address of the account able to transfer the tokens
    /// @return Amount of remaining tokens allowed to spent
    function allowance(address _owner, address _spender) constant returns (uint remaining) {}

    event Transfer(address indexed _from, address indexed _to, uint _value);
    event Approval(address indexed _owner, address indexed _spender, uint _value);
}

contract RegularToken is Token {

    function transfer(address _to, uint _value) returns (bool) {
        //Default assumes totalSupply can't be over max (2^256 - 1).
        if (balances[msg.sender] >= _value && balances[_to] + _value >= balances[_to]) {
            balances[msg.sender] -= _value;
            balances[_to] += _value;
            Transfer(msg.sender, _to, _value);
            return true;
        } else { return false; }
    }

    function transferFrom(address _from, address _to, uint _value) returns (bool) {
        if (balances[_from] >= _value && allowed[_from][msg.sender] >= _value && balances[_to] + _value >= balances[_to]) {
            balances[_to] += _value;
            balances[_from] -= _value;
            allowed[_from][msg.sender] -= _value;
            Transfer(_from, _to, _value);
            return true;
        } else { return false; }
    }

    function balanceOf(address _owner) constant returns (uint) {
        return balances[_owner];
    }

    function approve(address _spender, uint _value) returns (bool) {
        allowed[msg.sender][_spender] = _value;
        Approval(msg.sender, _spender, _value);
        return true;
    }

    function allowance(address _owner, address _spender) constant returns (uint) {
        return allowed[_owner][_spender];
    }

    mapping (address => uint) balances;
    mapping (address => mapping (address => uint)) allowed;
    uint public totalSupply;
}

contract UnboundedRegularToken is RegularToken {

    uint constant MAX_UINT = 2**256 - 1;
    
    /// @dev ERC20 transferFrom, modified such that an allowance of MAX_UINT represents an unlimited amount.
    /// @param _from Address to transfer from.
    /// @param _to Address to transfer to.
    /// @param _value Amount to transfer.
    /// @return Success of transfer.
    function transferFrom(address _from, address _to, uint _value)
        public
        returns (bool)
    {
        uint allowance = allowed[_from][msg.sender];
        if (balances[_from] >= _value
            && allowance >= _value
            && balances[_to] + _value >= balances[_to]
        ) {
            balances[_to] += _value;
            balances[_from] -= _value;
            if (allowance < MAX_UINT) {
                allowed[_from][msg.sender] -= _value;
            }
            Transfer(_from, _to, _value);
            return true;
        } else {
            return false;
        }
    }
}

contract ICToken is UnboundedRegularToken {

    uint public totalSupply = 1*10**27;
    uint8 constant public decimals = 18;
    string constant public name = "IIIBTC Coin";
    string constant public symbol = "IC";

    function ICToken() {
        balances[msg.sender] = totalSupply;
        Transfer(address(0), msg.sender, totalSupply);
    }
}
```

**Comment by yann300** [comment] 2018-08-13 08:44
i could deploy / verify it on ropsten and mainnet too...
https://ropsten.etherscan.io/verifyContract?a=0x66d3675f703a8292d629b1ca93270084d932401f
https://etherscan.io/address/0xe42e73c2c705ab07e134433092bb4ac28aeae635#code
please check if the selected version of solidity is 0.4.24

**Comment by whrool** [comment] 2018-08-13 08:50
Thank you. I will have a try myself. Hope it is my mistake.

**Comment by troowala** [comment] 2018-08-23 02:06
@yann300 have you seen the videos and what is your teams comments on it ? it clearly shows the issue. Can you please advise one way or other on this ?

Thanks

**Comment by smalaichami** [comment] 2018-09-11 09:15
The same here.. 

I deployed a token contract using remix-ide yesterday and not able to get it verified in Etherscan.
https://etherscan.io/tx/0xdd155456c9118273a5496dc222a66d55dd4becc287ad8a548a7b6637cf667ede

**Comment by cmaliwal** [comment] 2018-09-17 19:46
Yes, you can't verify your contract on etherscan if you deploy your code from remix and had optimisation is enabled . 

It's key point for every solidity developer , because I faced this issue one time and I spent my two night to verify my contract on etherscan but I didn't get any success , at the last I redeploy my contract with optimisation enabled .

**Comment by i-am-vivek** [comment] 2019-03-05 07:07
turning off the optimization helped me to verify the contract.

**Comment by yann300** [comment] 2019-05-11 15:18
the issue was related to https://github.com/ethereum/solidity/issues/5234 .
That should be fixed now.  i m closing it, please reopen if the issue is still here

**Closed by yann300** 2019-05-11 15:18 UTC
Labels: bug
