### ISSUE TITLE
Can't compile in firefox or load older compiler

### ISSUE THREAD

**Issue by unparalleled-js** [ethereum/remix-ide#1644] opened 2018-12-22 01:31 UTC
Hello. 
Currently was using Firefox to work with remix web IDE, but I had to switch to chrome because a few things with the compiler were not working...

First, I just could not compile a simple contract:

<img width="298" alt="screen shot 2018-12-21 at 7 29 13 pm" src="https://user-images.githubusercontent.com/19540978/50369192-da576e00-0556-11e9-85e1-ec8d95d482e5.png">
<img width="408" alt="screen shot 2018-12-21 at 7 29 16 pm" src="https://user-images.githubusercontent.com/19540978/50369193-dcb9c800-0556-11e9-86a7-03974f2716e6.png">

Then, when trying to pick an older compiler, it is stuck on "loading using worker".

I had no problem on Chrome however, but I am a firefox gal.

**Comment by yann300** [comment] 2019-01-02 10:56
cc @chriseth @axic

**Comment by chriseth** [comment] 2019-01-07 13:43
This is a bug in a certain version of the compiler - it does not work properly if the javascript runtime environment does not provide enough stack space or memory. It should work with the most recent compilers. Which version were you using and on which system and browser?

**Comment by axic** [comment] 2019-01-08 15:10
The same problem also reported in #1659.

**Comment by Masa331** [comment] 2019-01-15 09:00
Same for me on Firefox 64.0.2 (64-bit) on Arch Linux. It doesn't matter which compiler version i choose. It was working about a week ago but since then i think i did a packages update and i guess my Firefox could'v been updated from 64.0.1 as the update from 1-2 landed in package repositories on 10.1.2019

**Comment by yann300** [comment] 2019-01-15 14:10
@Masa331 tried with Firefox 64.0 I can't reproduce
is the issue always reproductible?
Could you send the stack of the 2 errors
`A network error occured` and `compileJSON is not a function`

thanks for helping

**Comment by codydjango** [comment] 2019-01-18 01:07
I'm using Firefox 64.0.2 (64-bit), and getting an `Internal exception` when attempting to compile ballot.sol using the most recent compiler `Current version:0.5.2+commit.1df8f40c.Emscripten.clang`

`Internal exception in StandardCompiler::compileInternal: /root/project/libevmasm/ExpressionClasses.cpp(187): Throw in function ExpressionClasses::Id dev::eth::ExpressionClasses::tryToSimplify(const dev::eth::ExpressionClasses::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::OptimizerException>
std::exception::what: Rule list not properly initialized.
[dev::tag_comment*] = Rule list not properly initialized.`

**Comment by axic** [comment] 2019-01-18 16:33
This will hopefully work again with 0.5.3 next week.

**Closed** 2019-01-18 16:32 UTC
Labels: bug
