### ISSUE TITLE
Use web workers to avoid freezing the UI during the compilation time.

### ISSUE THREAD

**Issue by stefek99** [ethereum/remix-ide#898] opened 2017-11-16 12:06 UTC
Auto compile option: any change triggers the compile, browser freezes for a number of seconds.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

> The worker thread can perform tasks without interfering with the user interface.

---

Workaround: I'm not using auto compilation as UI freeze is a pain.

**Comment by axic** [comment] 2018-02-26 09:49
Duplicate of #32. It is using a web workers, but not on all compilers due to weird issues produced by those.

**Closed by axic** 2018-02-26 09:49 UTC
