### ISSUE TITLE
Constant function returns nothing when order of call changes

### ISSUE THREAD

**Issue by HariPadBharti** [ethereum/remix-ide#1331] opened 2018-05-30 22:02 UTC
I wrote a simple contract to set a value, then increment, decrement and get the calculated value. I tried to get values without setting value and made get call, then set value, still don't get any value when I call get.  

Please find my code below and try to "get" first before "set", then "set" and call "get". 
```
pragma solidity ^0.4.0;

contract SimpleStorage{
    
    uint storedData;
    
    function set(uint x) public {
        
        storedData = x;
    }
    
    function get()  constant public returns (uint) {
        return storedData;
    }
    
    function increment (uint n) public{
        storedData = storedData + n;
        return;
    }
    
    function decrement (uint n) public {
        storedData = storedData - n;
        return;
    }
    
    
}
```

**Comment by yann300** [comment] 2018-05-31 06:08
calling `set` and then `get` works on remix.ethereum.org, are you using this?

**Comment by HariPadBharti** [comment] 2018-05-31 15:36
Yes, but if you do first `get` and then `set` doesn't work

**Comment by yann300** [comment] 2018-06-05 07:37
are you on the javascript VM? cause I can't reproduce...

**Comment by yann300** [comment] 2018-08-23 10:51
can't reproduce .... do you still have this issue?
closing it, please reopen if necessary

**Closed by yann300** 2018-08-23 10:51 UTC
Labels: bug
