### ISSUE TITLE
Set the status on unactivated module

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2365] opened 2019-09-24 17:01 UTC
got this while using the editor without having activated the solidity compiler: Got really strange behavior where the content of the file was duplicated multiple times....
```
Uncaught Error: Plugin solidity is currently deactivated. It cannot emit the event statusChanged. Activate solidity first
    at CompileTab.t.emit (app.js:3)
    at Object.onContentChanged (app.js:27946)
    at eventManager.trigger (app.js:19312)
    at Array.<anonymous> (app.js:27689)
    at EditSession.EventEmitter._signal (app.js:2
```

**Comment by LianaHus** [comment] 2020-07-23 12:42
@yann300 I can't reproduce this. could you please confirm so we can close the issue?

**Closed** 2020-07-27 08:32 UTC
Labels: bug
