### ISSUE TITLE
Possible Library Linkage problem on deployed contract at `remix-alpha`, that actually works on JavaScript mode

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/remix-ide#1254] opened 2018-04-13 08:09 UTC
I guess this error is related to following [closed issue][1], which still exists. The issue closed recommending us to use [remix-alpha][2], but `remix-alpha` still has the same error or I might be doing something wrong.

**=>** Is there anyone else face with similar error?

Deployed file names:

    Lib.sol         # Library contract //uses around 1,600,000 GAS to be deployed.
    myContract.sol  # Main contract    //uses around 3,400,000 GAS to be deployed.

I have tested my contract and it works perfectly fine on [populus][3] and remix's `JavaScript VM` mode. So there is no issue on the contract's code and its implementation. 

But whenever I deployed my contract on the `remix-alpha`; and tested my code on the deployed code as on `Web3 Provide mode`, if there is a call to Library function, the function call crashes (`thrown`) at that point. 

**I really don't know what causes this problem. This error is pretty annoying costing me hours and ether for each deployment, and facing contract does not work as it should be.**

As simplified, I have an emptied Library function call:

Lib.sol:

    /* Simple Library function */
    function constructCluster() public {
    
    }

When there is a call to that function; the function call is `reverted()`.

myContract.sol: `cluster.constructCluster(); //Contract is reverted()`

**[Q]** Is there anyway to fix this issue? I am out ot options. The only solution comes to my mind to merge main contact and Library contract but when I merge them I face with following error: `SolcError: InternalCompilerError: Static memory load of more than 32 bytes requested.`

=> Instead of using remix browser, if I deploy my contract from `geth-console` would it help to fix the problem?

----

_Note:_ I assume problem might be related with something else. I tried short files names, and it somehow used works at remix.org. But now, the exactly same contract works on remix-alpha's `JavaScript VM` mode but does not work (failing on Library function call) on remix's `JavaScript VM mode`.  Hence since it now does not work on remix's `JavaScript VM mode`, its deployed version on `Web3 Provide mode` also does not work even I use shorter files names. @Lauri Peltonen. 

  [1]: https://github.com/ethereum/remix-ide/issues/1110#issuecomment-372678216
  [2]: http://remix-alpha.ethereum.org
  [3]: https://github.com/ethereum/populus

**Comment by yann300** [comment] 2018-05-08 11:12
remix.ethereum.org has been updated today with a fix. could you double check that it fixes your issues please?
closing now, please reopen if necessary

**Comment by avatar-lavventura** [comment] 2018-05-08 11:34
@yann300  I have tried with the latest version (http://remix.ethereum.org/#optimize=false&version=soljson-v0.4.23+commit.124ca40d.js) I do still face with the same error.

**Comment by yann300** [comment] 2018-05-08 12:40
when you use `Web3 Provide mode` against which node are you connected to ? geth ?

**Comment by avatar-lavventura** [comment] 2018-05-08 19:30
I am using geth, and I am using private ethereum network. But I cam deploy my contract through geth console: Please see: https://ethereum.stackexchange.com/a/45792/4575

**Comment by yann300** [comment] 2018-05-09 08:15
do I reproduce by deploying the following `Array` and calling `myContract` ?

```
library Lib {
  uint80 constant None = uint80(0); // NULL.

  struct data {
    uint256 head;
    Node[100]  n;
    uint    size;
    uint    insert_number;
    uint    buffer_size;
  }

  struct Node {
    string  data;
    address owner;
    uint    own;
    uint    prev;
    uint    next;
  }

  function construct_me(data storage self){
    self.n[0].own      = 0;
    self.n[0].next     = 0;
    self.n[0].prev     = 0;
    self.head          = 0;

    self.insert_number = self.size = 1;

    self.buffer_size   = 100;
  }
}

contract owned {
  address  public owner;
  function owned() {
    owner = msg.sender;
  }
  function ownerOnly() {
    if (msg.sender != owner) throw;
  }
  modifier onlyOwner {
     if (msg.sender != owner) throw;
          _;
  }
  function transferOwnership(address newOwner) onlyOwner {
    owner = newOwner;
  }
}

contract Array is owned {
  using Lib for Lib.data;
  using Lib for Lib.Node;
  Lib.data list;

  function myContract(){
    if( test_callstack() != 1 ) throw;
    list.construct_me();
  }

  function test_callstack() constant returns ( int ){ return 1; }
}
```

**Comment by avatar-lavventura** [comment] 2018-05-09 11:53
I have simplified, please try this:
After calling `registerCluster()` then when you call `getClusterAddresses()`you should see registered cluster's address but it won't show up. 

```
library Lib {
    struct clusterData {
        bool isRunning; 
    }
  function constructCluster(clusterData storage self){
      self.isRunning         = true;
  }
}

contract Array {
  using Lib for Lib.clusterData;
  address[] clusterAddresses;
  mapping(address => Lib.clusterData) clusterContract;

  function registerCluster(){
     clusterContract[msg.sender].constructCluster();
     clusterAddresses.push(msg.sender);
  }
  
 function getClusterAddresses() public view
    returns (address[])
   {
    return clusterAddresses;
   }
}
```

**Comment by yann300** [comment] 2018-05-09 12:09
I am confused cause it works for me...
using javascript VM and also against geth 1.7.2 `geth --rpc --rpccorsdomain="*" --rpcapi web3,eth,debug,personal,net --vmdebug --ipcpath /home/yann/Ethereum/testchains/test2/geth.ipc --datadir /home/yann/Ethereum/testchains/test2/ --dev console` 

could you trying cleaning the browsre cache (or run remix-ide via npm module)

**Comment by avatar-lavventura** [comment] 2018-05-09 12:11
That's what I am trying to say. It works on `Javascript VM`. But when I deploy the contract using Web3 provider it does not work as a deployed contract.

**Comment by yann300** [comment] 2018-05-09 12:13
I also tried against `Web3 provider` and geth 1.7.2

**Comment by avatar-lavventura** [comment] 2018-05-09 12:13
```

Instructions
000 PUSH1 80
002 PUSH1 40
004 MSTORE
005 PUSH1 04
007 CALLDATASIZE
008 LT
009 PUSH2 004c
012 JUMPI
013 PUSH1 00
015 CALLDATALOAD
016 PUSH29 0100000000000000000000000000000000000000000000000000000000
046 SWAP1


Stack
0: 0x2d721f
1: 0x385e3177a4dc0e76f0fab9d87f7954a0c4c277fe
2: 0x80
3: 0x24
4: 0x80
5: 0x
6: 0xa4
7: 0x491c9430
8: 0x385e3177a4dc0e76f0fab9d87f7954a0c4c277fe
9: 0xd2
10: 0xa77bf742


Memory
0x0: 00000000000000000000000075a4c787	????????????u???
0x10: c5c18c587b284a904165ff06a269b48c	???X??J?Ae???i??
0x20: 00000000000000000000000000000000	????????????????
0x30: 00000000000000000000000000000001	????????????????
0x40: 00000000000000000000000000000000	????????????????
0x50: 00000000000000000000000000000080	????????????????
0x60: 00000000000000000000000000000000	????????????????
0x70: 00000000000000000000000000000000	????????????????
0x80: 491c9430faa331e372ba5d11d7a4e06c	I??0??1?r??????l
0x90: 4fa43a3354b4846c6a22703067057e87	O??3T??lj?p0g???
0xa0: a35089c2000000000000000000000000	?P??????????????
0xb0: 00000000000000000000000000000000	????????????????
```

**Comment by yann300** [comment] 2018-05-09 12:14
what backend are you using?

**Comment by LianaHus** [comment] 2020-07-22 12:48
@yann300  what is the state of this issue?

**Comment by yann300** [comment] 2020-07-27 12:21
we pushed a lot of fixed which also fixes some issues with libraries, please reopen if something is still not working

**Closed by yann300** 2020-07-27 12:21 UTC
Labels: bug, soon
