### ISSUE TITLE
setup bug

### ISSUE THREAD

**Issue by gheros** [ethereum/remix-ide#1388] opened 2018-07-04 05:38 UTC
npm install 
error

[build            ] 
[build            ] > remix-ide@0.6.4-alpha.1 build /home/g/remix-ide
[build            ] > browserify src/index.js -o build/app.js
[build            ] 
[build            ] SyntaxError: Maximum call stack size exceeded while parsing /home/g/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js while parsing file: /home/g/remix-ide/node_modules/remix-solidity/node_modules/solc/soljson.js
[build            ]     at DestroyableTransform.end [as _flush] (/home/g/remix-ide/node_modules/insert-module-globals/index.js:114:21)
[build            ]     at DestroyableTransform.prefinish (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_transform.js:138:10)
[build            ]     at emitNone (events.js:86:13)
[build            ]     at DestroyableTransform.emit (events.js:188:7)
[build            ]     at prefinish (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:619:14)
[build            ]     at finishMaybe (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:627:5)
[build            ]     at endWritable (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:638:3)
[build            ]     at DestroyableTransform.Writable.end (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_writable.js:594:41)
[build            ]     at DestroyableTransform.onend (/home/g/remix-ide/node_modules/readable-stream/lib/_stream_readable.js:577:10)
[build            ]     at Object.onceWrapper (events.js:293:19)
[build            ] 
[build            ] npm ERR! Linux 4.4.0-116-generic
[build            ] npm ERR! argv "/home/g/.nvm/versions/node/v7.10.1/bin/node" "/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js" "run" "build"
[build            ] npm ERR! node v7.10.1
[build            ] npm ERR! npm  v4.2.0
[build            ] npm ERR! code ELIFECYCLE
[build            ] npm ERR! errno 1
[build            ] npm ERR! remix-ide@0.6.4-alpha.1 build: `browserify src/index.js -o build/app.js`
[build            ] npm ERR! Exit status 1
[build            ] npm ERR! 
[build            ] npm ERR! Failed at the remix-ide@0.6.4-alpha.1 build script 'browserify src/index.js -o build/app.js'.
[build            ] npm ERR! Make sure you have the latest version of node.js and npm installed.
[build            ] npm ERR! If you do, this is most likely a problem with the remix-ide package,
[build            ] npm ERR! not with npm itself.
[build            ] npm ERR! Tell the author that this fails on your system:
[build            ] npm ERR!     browserify src/index.js -o build/app.js
[build            ] npm ERR! You can get information on how to open an issue for this project with:
[build            ] npm ERR!     npm bugs remix-ide
[build            ] npm ERR! Or if that isn't available, you can get their info via:
[build            ] npm ERR!     npm owner ls remix-ide
[build            ] npm ERR! There is likely additional logging output above.
[build            ] 
[build            ] npm ERR! Please include the following file with any support request:
[build            ] npm ERR!     /home/g/.npm/_logs/2018-07-04T04_08_42_347Z-debug.log

cat /home/g/.npm/_logs/2018-07-04T04_08_42_347Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/home/g/.nvm/versions/node/v7.10.1/bin/node',
1 verbose cli   '/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle remix-ide@0.6.4-alpha.1~prebuild: remix-ide@0.6.4-alpha.1
6 silly lifecycle remix-ide@0.6.4-alpha.1~prebuild: no script for prebuild, continuing
7 info lifecycle remix-ide@0.6.4-alpha.1~build: remix-ide@0.6.4-alpha.1
8 verbose lifecycle remix-ide@0.6.4-alpha.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle remix-ide@0.6.4-alpha.1~build: PATH: /home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/node-gyp-bin:/home/g/remix-ide/node_modules/.bin:/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/node-gyp-bin:/home/g/remix-ide/node_modules/.bin:/home/g/bin:/home/g/.local/bin:/home/g/.nvm/versions/node/v7.10.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle remix-ide@0.6.4-alpha.1~build: CWD: /home/g/remix-ide
11 silly lifecycle remix-ide@0.6.4-alpha.1~build: Args: [ '-c', 'browserify src/index.js -o build/app.js' ]
12 silly lifecycle remix-ide@0.6.4-alpha.1~build: Returned: code: 1  signal: null
13 info lifecycle remix-ide@0.6.4-alpha.1~build: Failed to exec build script
14 verbose stack Error: remix-ide@0.6.4-alpha.1 build: `browserify src/index.js -o build/app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid remix-ide@0.6.4-alpha.1
16 verbose cwd /home/g/remix-ide
17 error Linux 4.4.0-116-generic
18 error argv "/home/g/.nvm/versions/node/v7.10.1/bin/node" "/home/g/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js" "run" "build"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error remix-ide@0.6.4-alpha.1 build: `browserify src/index.js -o build/app.js`
23 error Exit status 1
24 error Failed at the remix-ide@0.6.4-alpha.1 build script 'browserify src/index.js -o build/app.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the remix-ide package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     browserify src/index.js -o build/app.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs remix-ide
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls remix-ide
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by jazzyarchitects** [comment] 2018-07-10 06:51
Duplicate of #1380

**Comment by fishmc** [comment] 2018-08-12 10:59
我也有这种情况

**Comment by yann300** [comment] 2018-08-23 10:55
That is fixed by now (added `--exclude solc` in the browserify script.

**Closed by yann300** 2018-08-23 10:55 UTC
Labels: Installation, bug
